export const UPDATE_USER = 'UPDATE_USER'

export const UPLOADING_PROFILE_PICTURE = 'UPLOADING_PROFILE_PICTURE'
export const FAILED_UPLOADING_PROFILE_PICTURE = 'FAILED_UPLOADING_PROFILE_PICTURE'
export const SUCCESS_UPLOADING_PROFILE_PICTURE = 'SUCCESS_UPLOADING_PROFILE_PICTURE'

export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE_IN_DB'
export const FAILED_UPDATING_PROFILE_PICTURE = 'FAILED_UPDATING_PROFILE_PICTURE_IN_DB'
export const SUCCESS_UPDATING_PROFILE_PICTURE = 'SUCCESS_UPDATING_PROFILE_PICTURE_IN_DB'
