
export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR'
export const CREATE_APPLICATION_SUCCESS = 'CREATE_APPLICATION_SUCCESS'
export const CREATE_APPLICATION_ERROR = 'CREATE_APPLICATION_ERROR'
export const MARK_AS_SEEN_SUCCESS = 'MARK_AS_SEEN_SUCCESS'
export const MARK_AS_SEEN_ERROR = 'MARK_AS_SEEN_ERROR'
