const APP_LOAD = 'APP_LOAD'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const POPULATE_OPPS = 'POPULATE_OPPS'
const GET_OPPS_APPLIED_FOR = 'GET_OPPS_APPLIED_FOR'
const UPDATE_USER = 'UPDATE_USER'

export {
  APP_LOAD,
  LOGIN,
  LOGOUT,
  POPULATE_OPPS,
  GET_OPPS_APPLIED_FOR,
  UPDATE_USER
}
