const APP_LOAD = 'APP_LOAD'
const LOGIN = 'LOGIN'
const LOGOUT = 'LOGOUT'
const POPULATE_OPPS = 'POPULATE_OPPS'
const GET_OPPS_APPLIED_FOR = 'GET_OPPS_APPLIED_FOR'
const APPLY_FOR_PROJECT = 'APPLY_FOR_PROJECT'
const FORGOT_PASSWORD = 'FORGOT_PASSWORD'

export {
  APP_LOAD,
  LOGIN,
  LOGOUT,
  POPULATE_OPPS,
  GET_OPPS_APPLIED_FOR,
  APPLY_FOR_PROJECT,
  FORGOT_PASSWORD
}
